'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")>  _
    Partial Friend NotInheritable Class SistemaKey
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As SistemaKey = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New SistemaKey()),SistemaKey)
        
        Public Shared ReadOnly Property [Default]() As SistemaKey
            Get
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Language() As String
            Get
                Return CType(Me("Language"),String)
            End Get
            Set
                Me("Language") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ColorProfile() As String
            Get
                Return CType(Me("ColorProfile"),String)
            End Get
            Set
                Me("ColorProfile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property UserProfile() As String
            Get
                Return CType(Me("UserProfile"),String)
            End Get
            Set
                Me("UserProfile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Newspoint Software - WinPersonalize")>  _
        Public Property SFNAME() As String
            Get
                Return CType(Me("SFNAME"),String)
            End Get
            Set
                Me("SFNAME") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("true")>  _
        Public Property AdvanceExplorerStyle() As String
            Get
                Return CType(Me("AdvanceExplorerStyle"),String)
            End Get
            Set
                Me("AdvanceExplorerStyle") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("true")>  _
        Public Property BackgroundExplorerImage() As String
            Get
                Return CType(Me("BackgroundExplorerImage"),String)
            End Get
            Set
                Me("BackgroundExplorerImage") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property SoftVersion() As String
            Get
                Return CType(Me("SoftVersion"),String)
            End Get
            Set
                Me("SoftVersion") = value
            End Set
        End Property
    End Class
End Namespace
